.PHONY: clean All

All:
	@echo "----------正在构建项目：[ Sort - Debug ]----------"
	@cd "Sort" && "$(MAKE)" -f  "Sort.mk"
clean:
	@echo "----------正在清理项目：[ Sort - Debug ]----------"
	@cd "Sort" && "$(MAKE)" -f  "Sort.mk" clean
